/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Invoice, Settlement, LedgerRow } from './types';

export const initialInvoices: Invoice[] = [
  {
    id: 'INV-2026-089',
    obligor: 'Global Motors Corp',
    supplier: 'Mechano-Tech Labs',
    logoType: 'motors',
    faceValue: 142500,
    discount: 2.0, // 2% dynamic yield
    maturity: 44,
    status: 'Available',
    buyerRating: 'A+',
    buyerScore: 94,
    poNumber: 'PO-9902-XLY-01',
    poDate: 'July 12, 2026',
    grnWarehouse: 'Warehouse 04',
    grnDate: 'July 28, 2026',
    signatureName: 'Martha Wayne',
    signatureDivision: 'Treasury',
    signatureDate: 'Aug 02, 2026',
    description: 'Precision engineering automotive components for Global Motors Corp EV platform transition.',
    verityScore: 94,
    paymentDelinquency: 0.02,
    avgDaysBeyondTerm: 0.4,
    disputeRatio: 0.0,
    retentionReleaseRate: 100,
    marketCap: '$54.2B',
    spRating: 'A-',
    nyseSymbol: 'GM'
  },
  {
    id: 'INV-88219',
    obligor: 'Global Logistics Corp',
    supplier: 'Express Freight Inc',
    logoType: 'logistics',
    faceValue: 450200,
    discount: 1.8,
    maturity: 32,
    status: 'Available',
    buyerRating: 'A',
    buyerScore: 92,
    poNumber: 'PO-7841-LOG-09',
    poDate: 'July 15, 2026',
    grnWarehouse: 'Terminal 03 Depot',
    grnDate: 'July 29, 2026',
    signatureName: 'Richard Grayson',
    signatureDivision: 'Supply Chain Operations',
    signatureDate: 'Aug 04, 2026',
    description: 'Intermodal freight forwarding and distribution services for Northern European routes.',
    verityScore: 92,
    paymentDelinquency: 0.05,
    avgDaysBeyondTerm: 0.8,
    disputeRatio: 0.1,
    retentionReleaseRate: 100,
    marketCap: '$28.4B',
    spRating: 'A',
    nyseSymbol: 'GLC'
  },
  {
    id: 'INV-88220',
    obligor: 'TechNode Assembly',
    supplier: 'Silicon Foundry Ltd',
    logoType: 'assembly',
    faceValue: 1240000,
    discount: 2.1,
    maturity: 45,
    status: 'Available',
    buyerRating: 'AA',
    buyerScore: 96,
    poNumber: 'PO-5512-TNA-102',
    poDate: 'July 01, 2026',
    grnWarehouse: 'Cleanroom Lab 08',
    grnDate: 'July 20, 2026',
    signatureName: 'Timothy Drake',
    signatureDivision: 'Procurement QA',
    signatureDate: 'July 25, 2026',
    description: 'System-on-chip assemblies and microprocessor packaging for enterprise hardware clients.',
    verityScore: 96,
    paymentDelinquency: 0.01,
    avgDaysBeyondTerm: 0.1,
    disputeRatio: 0.0,
    retentionReleaseRate: 100,
    marketCap: '$112.5B',
    spRating: 'AA-',
    nyseSymbol: 'TNA'
  },
  {
    id: 'INV-88224',
    obligor: 'SolarFlow Renewables',
    supplier: 'Helios Panel Corp',
    logoType: 'renewables',
    faceValue: 285400,
    discount: 1.5,
    maturity: 18,
    status: 'Available',
    buyerRating: 'A-',
    buyerScore: 89,
    poNumber: 'PO-Solar-4011',
    poDate: 'July 18, 2026',
    grnWarehouse: 'Solar Grid Array B',
    grnDate: 'August 01, 2026',
    signatureName: 'Selina Kyle',
    signatureDivision: 'Infrastructure Finance',
    signatureDate: 'August 06, 2026',
    description: 'Photovoltaic cells and energy storage buffer modules for utility-scale grid arrays.',
    verityScore: 89,
    paymentDelinquency: 0.08,
    avgDaysBeyondTerm: 1.2,
    disputeRatio: 0.05,
    retentionReleaseRate: 98,
    marketCap: '$14.9B',
    spRating: 'BBB+',
    nyseSymbol: 'SFR'
  },
  {
    id: 'INV-88229',
    obligor: 'Prime Retail Dist.',
    supplier: 'Aura Packaging Co',
    logoType: 'retail',
    faceValue: 95000,
    discount: 2.4,
    maturity: 60,
    status: 'Available',
    buyerRating: 'B+',
    buyerScore: 82,
    poNumber: 'PO-PRD-88902',
    poDate: 'June 25, 2026',
    grnWarehouse: 'Distribution Hub East',
    grnDate: 'July 15, 2026',
    signatureName: 'Alfred Pennyworth',
    signatureDivision: 'Logistics Liaison',
    signatureDate: 'July 22, 2026',
    description: 'Eco-friendly biodegradable structural packaging and shipping materials for Prime Global Retailers.',
    verityScore: 82,
    paymentDelinquency: 0.15,
    avgDaysBeyondTerm: 2.5,
    disputeRatio: 0.2,
    retentionReleaseRate: 100,
    marketCap: '$8.7B',
    spRating: 'BB+',
    nyseSymbol: 'PRD'
  },
  // Screen 2 Cards Invoices:
  {
    id: 'INV-0054',
    obligor: 'SmallCorp Ltd',
    supplier: 'Acme Corp',
    logoType: 'tech',
    faceValue: 50000,
    discount: 2.5,
    maturity: 30,
    status: 'Available',
    buyerRating: 'AAA',
    buyerScore: 98,
    poNumber: 'PO-ACME-00212',
    poDate: 'July 10, 2026',
    grnWarehouse: 'Acme Depot #2',
    grnDate: 'July 22, 2026',
    signatureName: 'Wile E. Coyote',
    signatureDivision: 'R&D Operations',
    signatureDate: 'July 27, 2026',
    description: 'Heavy duty testing equipment and technical simulation instrumentation.',
    verityScore: 98,
    paymentDelinquency: 0.0,
    avgDaysBeyondTerm: 0.0,
    disputeRatio: 0.05,
    retentionReleaseRate: 100,
    marketCap: '$1.4B',
    spRating: 'AA+',
    nyseSymbol: 'SMLC'
  },
  {
    id: 'INV-0055',
    obligor: 'Vendor XYZ',
    supplier: 'Global Tech',
    logoType: 'assembly',
    faceValue: 120000,
    discount: 3.2,
    maturity: 45,
    status: 'Available',
    buyerRating: 'A-',
    buyerScore: 85,
    poNumber: 'PO-GT-50031',
    poDate: 'July 05, 2026',
    grnWarehouse: 'Storage Center Omega',
    grnDate: 'July 26, 2026',
    signatureName: 'Barbara Gordon',
    signatureDivision: 'Information Systems',
    signatureDate: 'August 01, 2026',
    description: 'Server rack infrastructure cooling systems and fiber optic network switch units.',
    verityScore: 85,
    paymentDelinquency: 0.12,
    avgDaysBeyondTerm: 1.4,
    disputeRatio: 0.08,
    retentionReleaseRate: 99,
    marketCap: '$5.8B',
    spRating: 'BBB',
    nyseSymbol: 'VXYZ'
  },
  {
    id: 'INV-0056',
    obligor: 'Service Prov.',
    supplier: 'Fortune 500 Co',
    logoType: 'retail',
    faceValue: 250000,
    discount: 1.8,
    maturity: 20,
    status: 'Available',
    buyerRating: 'AAA',
    buyerScore: 99,
    poNumber: 'PO-F5C-11229',
    poDate: 'July 20, 2026',
    grnWarehouse: 'Fulfillment HQ',
    grnDate: 'August 04, 2026',
    signatureName: 'Lucius Fox',
    signatureDivision: 'Operations Control',
    signatureDate: 'August 09, 2026',
    description: 'Strategic hardware consulting services and outsourced data-center deployment.',
    verityScore: 99,
    paymentDelinquency: 0.005,
    avgDaysBeyondTerm: 0.02,
    disputeRatio: 0.0,
    retentionReleaseRate: 100,
    marketCap: '$240.5B',
    spRating: 'AAA',
    nyseSymbol: 'FVS'
  }
];

export const initialSettlements: Settlement[] = [
  {
    id: 'INV-77412',
    invoiceId: 'INV-77412',
    payer: 'Oracle Global Services',
    amount: 124550.00,
    yieldEarned: 2491.00,
    timeAgo: '2h ago',
    status: 'Settled',
    date: '2026-05-31'
  },
  {
    id: 'INV-77405',
    invoiceId: 'INV-77405',
    payer: 'Microsoft Corp',
    amount: 88200.00,
    yieldEarned: 1764.00,
    timeAgo: '5h ago',
    status: 'Settled',
    date: '2026-05-31'
  },
  {
    id: 'INV-77418',
    invoiceId: 'INV-77418',
    payer: 'Amazon Logistics',
    amount: 315400.00,
    yieldEarned: 0,
    timeAgo: 'Yesterday',
    status: 'Pending',
    date: '2026-05-30'
  },
  {
    id: 'INV-0012',
    invoiceId: 'INV-0012',
    payer: 'Intel Assembly Inc',
    amount: 50000,
    yieldEarned: 1250,
    timeAgo: '11 days ago',
    status: 'Settled',
    date: '2026-05-20'
  },
  {
    id: 'INV-0011',
    invoiceId: 'INV-0011',
    payer: 'Logitech Wholesale',
    amount: 38000,
    yieldEarned: 950,
    timeAgo: '13 days ago',
    status: 'Settled',
    date: '2026-05-18'
  },
  {
    id: 'INV-0010',
    invoiceId: 'INV-0010',
    payer: 'AMD Packing Corp',
    amount: 120000,
    yieldEarned: 2100,
    timeAgo: '16 days ago',
    status: 'Settled',
    date: '2026-05-15'
  }
];

export const initialLedger: LedgerRow[] = [
  {
    invoiceId: 'INV-88219',
    obligor: 'Global Logistics Corp',
    faceValue: 42000,
    yieldEarned: 842.12,
    settlementDate: 'Oct 12, 2023',
    status: 'SETTLED'
  },
  {
    invoiceId: 'INV-88224',
    obligor: 'Atlas Manufacturing',
    faceValue: 115500,
    yieldEarned: 2415.00,
    settlementDate: 'Oct 10, 2023',
    status: 'SETTLED'
  },
  {
    invoiceId: 'INV-88231',
    obligor: 'Nexus Retail Partners',
    faceValue: 18200,
    yieldEarned: 312.45,
    settlementDate: 'Oct 09, 2023',
    status: 'SETTLED'
  },
  {
    invoiceId: 'INV-88245',
    obligor: 'Terra-Form Dynamics',
    faceValue: 67000,
    yieldEarned: 1288.90,
    settlementDate: 'Oct 05, 2023',
    status: 'SETTLED'
  }
];

export const initialHistoricalPerformance = [
  { month: 'Jan', yield: 4.8, benchmark: 4.5 },
  { month: 'Mar', yield: 5.9, benchmark: 4.8 },
  { month: 'May', yield: 6.8, benchmark: 5.2 },
  { month: 'Jul', yield: 7.4, benchmark: 5.8 },
  { month: 'Sep', yield: 8.2, benchmark: 6.5 },
  { month: 'Nov', yield: 9.1, benchmark: 7.2 }
];
